# -*- coding: utf-8 -*-
"""🌾 Seasonal Agriculture Performance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UStHQGXEdrux1-cjcw4QAybm5fYQw73R

# **Install libraries**
"""

# Run this cell in Google Colab if required

!pip install pandas numpy matplotlib seaborn scipy scikit-learn openpyxl

"""# **Import Libraries**"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

"""# **Load Dataset**"""

FILE_PATH = "/content/seasonal_agriculture_performance_dataset.csv"

df = pd.read_csv(FILE_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

"""# **Basic Dataset Exploration**"""

print("=" * 60)
print("DATASET INFORMATION")
print("=" * 60)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 5 Records:")
display(df.head())

"""# **Dataset Information**"""

print("\nDATA TYPES")
print("-" * 50)

print(df.dtypes)

print("\nDATASET INFO")
print("-" * 50)

df.info()

"""# **Statistical Summary**"""

print("STATISTICAL SUMMARY")
display(df.describe(include="all").T)

"""# **Missing Value Analysis**"""

missing = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing = missing.sort_values(
    "Missing_Percentage",
    ascending=False
)

display(missing)

"""# **Missing-value visualization**"""

plt.figure(figsize=(12, 6))

sns.barplot(
    x=missing["Missing_Percentage"],
    y=missing["Column"]
)

plt.title("Missing Values by Column")
plt.xlabel("Missing Percentage (%)")
plt.ylabel("Column")

plt.show()

"""# **Duplicate Analysis**"""

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

"""# **Clean Column Names**"""

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

print(df.columns.tolist())

"""# **Data Cleaning**

# **Numerical columns**
"""

numeric_columns = df.select_dtypes(
    include=np.number
).columns

for col in numeric_columns:

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

    df[col] = df[col].fillna(
        df[col].median()
    )

"""# **Categorical columns**"""

categorical_columns = df.select_dtypes(
    include="object"
).columns

for col in categorical_columns:

    if df[col].isnull().sum() > 0:

        mode_value = df[col].mode()

        if len(mode_value) > 0:
            df[col] = df[col].fillna(
                mode_value[0]
            )

"""# **Verify Cleaning**"""

print("Remaining missing values:")

print(
    df.isnull().sum()
    .sort_values(ascending=False)
    .head(20)
)

"""# **Unique Seasons**"""

if season_col:

    print("Available Seasons:")

    print(
        df[season_col]
        .value_counts()
    )

"""# **Seasonal Distribution**"""

if season_col:

    plt.figure(figsize=(10, 6))

    sns.countplot(
        data=df,
        x=season_col,
        order=df[season_col].value_counts().index
    )

    plt.title("Distribution of Agricultural Records by Season")

    plt.xticks(rotation=45)

    plt.show()

"""# **Agricultural Performance Across Seasons**"""

if season_col:

    plt.figure(figsize=(10, 6))

    sns.countplot(
        data=df,
        x=season_col,
        order=df[season_col].value_counts().index
    )

    plt.title("Distribution of Agricultural Records by Season")

    plt.xticks(rotation=45)

    plt.show()

"""# **Average Production by Season**"""

if season_col and production_col:

    seasonal_performance = (
        df.groupby(season_col)[production_col]
        .agg([
            "count",
            "mean",
            "median",
            "min",
            "max",
            "std"
        ])
        .sort_values("mean", ascending=False)
    )

    display(seasonal_performance)

"""# **Production Variation by Season**"""

if season_col and production_col:

    plt.figure(figsize=(12, 6))

    sns.boxplot(
        data=df,
        x=season_col,
        y=production_col
    )

    plt.title("Production Variation Across Seasons")

    plt.xticks(rotation=45)

    plt.show()

"""# **Crop-wise Seasonal Analysis**"""

if season_col and crop_col and production_col:

    crop_season = pd.pivot_table(
        df,
        values=production_col,
        index=crop_col,
        columns=season_col,
        aggfunc="mean"
    )

    display(crop_season)

"""# **Crop × Season Heatmap**"""

if season_col and crop_col and production_col:

    plt.figure(figsize=(14, 8))

    sns.heatmap(
        crop_season,
        annot=True,
        fmt=".2f",
        cmap="YlGnBu"
    )

    plt.title(
        "Average Production by Crop and Season"
    )

    plt.xlabel("Season")
    plt.ylabel("Crop")

    plt.show()

"""# **Regional Seasonal Analysis**"""

if region_col and season_col and production_col:

    regional_seasonal = pd.pivot_table(
        df,
        values=production_col,
        index=region_col,
        columns=season_col,
        aggfunc="mean"
    )

    display(regional_seasonal)

"""# **Regional Performance Heatmap**"""

if region_col and season_col and production_col:

    plt.figure(figsize=(14, 8))

    sns.heatmap(
        regional_seasonal,
        annot=True,
        fmt=".1f",
        cmap="viridis"
    )

    plt.title(
        "Regional Agricultural Performance Across Seasons"
    )

    plt.xlabel("Season")
    plt.ylabel("Region")

    plt.show()

"""# **Environmental Conditions by Season**

# **Rainfall by Season**
"""

if season_col and rainfall_col:

    rainfall_season = (
        df.groupby(season_col)[rainfall_col]
        .mean()
        .sort_values(ascending=False)
    )

    display(rainfall_season)

if season_col and rainfall_col:

    plt.figure(figsize=(10, 6))

    sns.barplot(
        x=rainfall_season.index,
        y=rainfall_season.values
    )

    plt.title("Average Rainfall Across Seasons")

    plt.xlabel("Season")
    plt.ylabel("Average Rainfall")

    plt.xticks(rotation=45)

    plt.show()

"""# **Temperature by Season**"""

temperature_col = find_column(
    df.columns,
    ["temperature", "temp"]
)

print("Temperature column:", temperature_col)

if season_col and temperature_col:

    temperature_season = (
        df.groupby(season_col)[temperature_col]
        .mean()
    )

    plt.figure(figsize=(10, 6))

    sns.barplot(
        x=temperature_season.index,
        y=temperature_season.values
    )

    plt.title(
        "Average Temperature Across Seasons"
    )

    plt.xlabel("Season")
    plt.ylabel("Temperature")

    plt.xticks(rotation=45)

    plt.show()

"""# **Humidity by Season**"""

humidity_col = find_column(
    df.columns,
    ["humidity", "moisture"]
)

print("Humidity column:", humidity_col)

if season_col and humidity_col:

    humidity_season = (
        df.groupby(season_col)[humidity_col]
        .mean()
    )

    plt.figure(figsize=(10, 6))

    sns.barplot(
        x=humidity_season.index,
        y=humidity_season.values
    )

    plt.title(
        "Average Humidity Across Seasons"
    )

    plt.xlabel("Season")
    plt.ylabel("Humidity")

    plt.xticks(rotation=45)

    plt.show()

"""# **Resource Usage Analysis**"""

resource_keywords = [
    "water",
    "irrigation",
    "fertilizer",
    "pesticide",
    "labor",
    "labour",
    "seed",
    "fuel",
    "electricity",
    "resource"
]

resource_columns = []

for col in df.columns:

    if any(
        keyword in col.lower()
        for keyword in resource_keywords
    ):

        if pd.api.types.is_numeric_dtype(df[col]):

            resource_columns.append(col)

print("Resource columns:")
print(resource_columns)

"""# **Resource Usage Visualization**"""

if season_col and resource_columns:

    resource_season = (
        df.groupby(season_col)[resource_columns]
        .mean()
    )

    display(resource_season)

if season_col and resource_columns:

    resource_season.plot(
        kind="bar",
        figsize=(14, 7)
    )

    plt.title(
        "Average Resource Usage Across Seasons"
    )

    plt.xlabel("Season")
    plt.ylabel("Average Usage")

    plt.xticks(rotation=45)

    plt.legend(
        bbox_to_anchor=(1.05, 1),
        loc="upper left"
    )

    plt.tight_layout()

    plt.show()

"""# **Economic Performance**

# **Revenue by Season**
"""

revenue_col = find_column(
    df.columns,
    ["revenue", "income", "sales", "economic"]
)

print("Revenue column:", revenue_col)

cost_col = find_column(
    df.columns,
    ["cost", "expense", "expenditure"]
)

print("Cost column:", cost_col)

"""# **Profit Calculation**"""

if revenue_col and cost_col:

    df["profit"] = (
        df[revenue_col] -
        df[cost_col]
    )

    print("Profit column created successfully.")

if season_col and "profit" in df.columns:

    seasonal_profit = (
        df.groupby(season_col)["profit"]
        .agg([
            "mean",
            "median",
            "min",
            "max",
            "std"
        ])
        .sort_values(
            "mean",
            ascending=False
        )
    )

    display(seasonal_profit)

"""# **Profit Visualization**"""

if season_col and "profit" in df.columns:

    plt.figure(figsize=(10, 6))

    sns.boxplot(
        data=df,
        x=season_col,
        y="profit"
    )

    plt.title(
        "Profit Distribution Across Seasons"
    )

    plt.xticks(rotation=45)

    plt.show()

"""# **Correlation Analysis**"""

numeric_df = df.select_dtypes(
    include=np.number
)

correlation_matrix = numeric_df.corr()

display(correlation_matrix)

"""# **Correlation Heatmap**"""

plt.figure(figsize=(14, 10))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0
)

plt.title(
    "Correlation Between Agricultural Variables"
)

plt.show()

"""# **Environmental Condition vs Production**

# **Rainfall vs Production**
"""

if rainfall_col and production_col:

    plt.figure(figsize=(10, 6))

    sns.scatterplot(
        data=df,
        x=rainfall_col,
        y=production_col,
        hue=season_col if season_col else None
    )

    plt.title(
        "Rainfall vs Agricultural Production"
    )

    plt.xlabel("Rainfall")
    plt.ylabel("Production")

    plt.show()

"""# **Temperature vs Production**"""

if temperature_col and production_col:

    plt.figure(figsize=(10, 6))

    sns.scatterplot(
        data=df,
        x=temperature_col,
        y=production_col,
        hue=season_col if season_col else None
    )

    plt.title(
        "Temperature vs Agricultural Production"
    )

    plt.xlabel("Temperature")
    plt.ylabel("Production")

    plt.show()

"""# **Humidity vs Production**"""

if humidity_col and production_col:

    plt.figure(figsize=(10, 6))

    sns.scatterplot(
        data=df,
        x=humidity_col,
        y=production_col,
        hue=season_col if season_col else None
    )

    plt.title(
        "Humidity vs Agricultural Production"
    )

    plt.xlabel("Humidity")
    plt.ylabel("Production")

    plt.show()

"""# **Statistical Test — Seasonal Difference**"""

if season_col and production_col:

    season_groups = []

    season_names = []

    for season, group in df.groupby(season_col):

        if len(group) >= 2:

            season_groups.append(
                group[production_col].dropna()
            )

            season_names.append(season)

    if len(season_groups) >= 2:

        f_stat, p_value = stats.f_oneway(
            *season_groups
        )

        print("ANOVA Results")
        print("-" * 40)

        print("F-statistic:", f_stat)
        print("P-value:", p_value)

        alpha = 0.05

        if p_value < alpha:

            print(
                "Result: Significant difference "
                "in production across seasons."
            )

        else:

            print(
                "Result: No statistically significant "
                "difference detected across seasons."
            )

"""# **Seasonal Performance Ranking**"""

if season_col and production_col:

    seasonal_ranking = (
        df.groupby(season_col)[production_col]
        .mean()
        .sort_values(
            ascending=False
        )
        .reset_index()
    )

    seasonal_ranking["Rank"] = range(
        1,
        len(seasonal_ranking) + 1
    )

    display(seasonal_ranking)

"""# **Identify Best and Worst Season**"""

if season_col and production_col:

    best_season = seasonal_ranking.iloc[0]

    worst_season = seasonal_ranking.iloc[-1]

    print(
        "Best performing season:",
        best_season[season_col]
    )

    print(
        "Average production:",
        round(
            best_season[production_col],
            2
        )
    )

    print()

    print(
        "Lowest performing season:",
        worst_season[season_col]
    )

    print(
        "Average production:",
        round(
            worst_season[production_col],
            2
        )
    )

"""# **Outlier Detection**"""

def detect_outliers(data, column):

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower) |
        (data[column] > upper)
    ]

    return outliers

"""# **Production Outliers**"""

if season_col and production_col:

    seasonal_stats = (
        df.groupby(season_col)[production_col]
        .agg(["mean", "std"])
    )

    df["season_mean"] = df[
        season_col
    ].map(
        seasonal_stats["mean"]
    )

    df["season_std"] = df[
        season_col
    ].map(
        seasonal_stats["std"]
    )

    df["season_zscore"] = (
        df[production_col] -
        df["season_mean"]
    ) / df["season_std"].replace(
        0,
        np.nan
    )

    unusual_records = df[
        abs(df["season_zscore"]) > 2
    ]

    print(
        "Unusual seasonal observations:",
        len(unusual_records)
    )

    display(
        unusual_records.head(20)
    )

"""# **Machine Learning Feature Importance**"""

if production_col:

    ml_df = df.select_dtypes(
        include=np.number
    ).copy()

    ml_df = ml_df.dropna()

    if production_col in ml_df.columns:

        X = ml_df.drop(
            columns=[production_col]
        )

        y = ml_df[production_col]

        if X.shape[1] > 0 and len(X) >= 10:

            X_train, X_test, y_train, y_test = train_test_split(
                X,
                y,
                test_size=0.2,
                random_state=42
            )

            model = RandomForestRegressor(
                n_estimators=200,
                random_state=42
            )

            model.fit(
                X_train,
                y_train
            )

            predictions = model.predict(
                X_test
            )

            print(
                "MAE:",
                mean_absolute_error(
                    y_test,
                    predictions
                )
            )

            print(
                "RMSE:",
                np.sqrt(
                    mean_squared_error(
                        y_test,
                        predictions
                    )
                )
            )

            print(
                "R²:",
                r2_score(
                    y_test,
                    predictions
                )
            )

"""# **Feature Importance**"""

if 'model' in globals():

    feature_importance = pd.DataFrame({

        "Feature": X.columns,

        "Importance": model.feature_importances_

    }).sort_values(
        "Importance",
        ascending=False
    )

    display(feature_importance)

"""# **Feature Importance Graph**"""

if 'feature_importance' in globals():

    plt.figure(figsize=(10, 7))

    sns.barplot(
        data=feature_importance.head(15),
        x="Importance",
        y="Feature"
    )

    plt.title(
        "Top Factors Associated with Agricultural Production"
    )

    plt.show()

"""# **Generate Automatic Key Findings**"""

print("=" * 70)
print("KEY AGRICULTURAL FINDINGS")
print("=" * 70)

if season_col and production_col:

    best = (
        df.groupby(season_col)[production_col]
        .mean()
        .idxmax()
    )

    worst = (
        df.groupby(season_col)[production_col]
        .mean()
        .idxmin()
    )

    best_value = (
        df.groupby(season_col)[production_col]
        .mean()
        .max()
    )

    worst_value = (
        df.groupby(season_col)[production_col]
        .mean()
        .min()
    )

    print(
        f"1. Highest average production was observed "
        f"during {best} ({best_value:.2f})."
    )

    print(
        f"2. Lowest average production was observed "
        f"during {worst} ({worst_value:.2f})."
    )

    print(
        f"3. Difference between the highest and lowest "
        f"seasonal average: "
        f"{best_value - worst_value:.2f}"
    )

"""# **Automatically Generate Recommendations**"""

print("=" * 70)
print("DATA-DRIVEN RECOMMENDATIONS")
print("=" * 70)

if season_col and production_col:

    print(
        f"• Prioritize agricultural planning during "
        f"the higher-performing season: {best}."
    )

    print(
        f"• Investigate environmental and resource "
        f"conditions associated with the lower-performing "
        f"season: {worst}."
    )

if rainfall_col and production_col:

    corr = df[
        [rainfall_col, production_col]
    ].corr().iloc[0, 1]

    if corr > 0.3:

        print(
            "• Rainfall shows a positive relationship "
            "with production; water availability should "
            "be considered in seasonal planning."
        )

    elif corr < -0.3:

        print(
            "• Rainfall shows a negative relationship "
            "with production; excessive rainfall or "
            "related conditions may require investigation."
        )

    else:

        print(
            "• Rainfall has a weak linear relationship "
            "with production in the available data."
        )

"""# **Create Final Summary Table**"""

summary_tables = {}

if season_col and production_col:

    summary_tables["Seasonal Performance"] = (
        df.groupby(season_col)[production_col]
        .agg(
            Average="mean",
            Median="median",
            Minimum="min",
            Maximum="max",
            Std_Deviation="std"
        )
        .round(2)
    )

if season_col and revenue_col:

    summary_tables["Seasonal Revenue"] = (
        df.groupby(season_col)[revenue_col]
        .mean()
        .round(2)
        .to_frame("Average Revenue")
    )

if season_col and rainfall_col:

    summary_tables["Seasonal Rainfall"] = (
        df.groupby(season_col)[rainfall_col]
        .mean()
        .round(2)
        .to_frame("Average Rainfall")
    )

for name, table in summary_tables.items():

    print("\n", "=" * 60)
    print(name)
    print("=" * 60)

    display(table)

"""# **“Develop your own specific analytical questions”**

| No.     | Our analytical question                                                                   | Analysis                          |
| ------- | ----------------------------------------------------------------------------------------- | --------------------------------- |
| **Q1**  | Which season has the highest and lowest agricultural production?                          | Seasonal production comparison    |
| **Q2**  | Which crops perform best and worst within each season?                                    | Crop × Season analysis            |
| **Q3**  | Which region shows the highest agricultural performance in each season?                   | Region × Season analysis          |
| **Q4**  | How does crop production vary across different seasons?                                   | Box plot + statistical comparison |
| **Q5**  | Which environmental factor has the strongest relationship with agricultural production?   | Correlation analysis              |
| **Q6**  | Does rainfall significantly affect agricultural production?                               | Correlation + scatter plot        |
| **Q7**  | How does resource usage such as water, fertilizer, or labor vary between seasons?         | Resource analysis                 |
| **Q8**  | Which season provides the best economic performance based on revenue, cost, or profit?    | Economic analysis                 |
| **Q9**  | Are there unusual production values or seasonal patterns that require investigation?      | Outlier/anomaly analysis          |
| **Q10** | Are the differences in agricultural production between seasons statistically significant? | ANOVA                             |
"""